services:
  db:
    image: mariadb:10.11
    container_name: nc_db
    command: >
      --transaction-isolation=READ-COMMITTED
      --binlog-format=ROW
      --innodb-read-only-compressed=OFF
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - TZ=${TZ}
    volumes:
      - /srv/storage/nextcloud/db:/var/lib/mysql
    restart: unless-stopped
    networks: [internal]

  redis:
    image: redis:7-alpine
    container_name: nc_redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    networks: [internal]

  nextcloud:
    image: nextcloud:apache
    container_name: nextcloud
    depends_on: [db, redis]
    ports:
      - "${HTTP_PORT}:80"          # LAN/VPN only (no public forward)
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - PHP_MEMORY_LIMIT=512M
      - TZ=${TZ}
    volumes:
      # app code + config
      - /srv/storage/nextcloud/app:/var/www/html
      # user files live in data/
      - /srv/storage/nextcloud/data:/var/www/html/data
    restart: unless-stopped
    networks:
      - internal
      - default

networks:
  internal:
    driver: bridge
    internal: true
    